apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4002
      targetPort: 4002
  selector:
    app: post-service