apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4001
      targetPort: 4001
  selector:
    app: auth-service