apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: microservices
spec:
  type: NodePort
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30173
  selector:
    app: client