apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: registration-service
        image: nghiax1609/registration-service:1.0.0
        ports:
        - containerPort: 4003
        env:
        - name: PORT
          value: "4003"
        - name: DATABASE_URL
          value: "postgresql://userdb_xf0e_user:GdcIqbOFlhgkJtQnTVSFDItAFZfpq9YL@dpg-d15dcpm3jp1c73fp4fig-a.singapore-postgres.render.com/userdb_xf0e"