apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4003
      targetPort: 4003
  selector:
    app: registration-service